---
title: 'Desemprego e rendimento: Números reais do Brasil'
date: "`r Sys.Date()`"
author: "Gladson Rabelo | gladsonrf1@gmail.com"
output: pdf_document
---

# Taxa de desemprego (desocupação)

# Rendimento médio real mensal habitualmente recebido

# Rendimento médio real mensal habitualmente recebido por posição na ocupação

# Quantidade de pessoas ocupadas por posição na ocupação

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Carregando pacotes
pacman::p_load(tidyverse,lubridate,sidrar,zoo,scales,timetk,magrittr,
               xts,dplyr,tidyr,showtext,ggplot2)
```

```{r, message=FALSE, message=FALSE, echo=FALSE}
#Coletando dados populacionais
urlpopulacao="/t/6022/n1/all/v/606/p/all"
populacao = get_sidra(api=urlpopulacao) %>% 
  #tratamento da data
  mutate(date = parse_date(`Trimestre Móvel (Código)`,
                           format='%Y%m')) %>% 
  #selecione só as variáveis que vai usar
  select(date,Valor) %>% 
  as_tibble()

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Condição em relação à força de trabalho e condição de ocupação
#criando um novo objeto pra usar posteriormente
names = c("date", "pnea", "pea", "desocupada", "ocupada", "pia")

#Coleta de dados
urlcondicao="/t/6318/n1/all/v/1641/p/all/c629/all"
condicao = get_sidra(api=urlcondicao) %>% 
  mutate(date = parse_date(`Trimestre Móvel (Código)`,
                           format = "%Y%m")) %>% 
  select(date,"Condição em relação à força de trabalho e condição de ocupação",
         Valor) %>%
  #pivotezação rapida transformando as observações em colunas
  spread(`Condição em relação à força de trabalho e condição de ocupação`,
         Valor) %>%
  `colnames<-`(names) %>% 
  as_tibble()
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Juntando os dados, renomeando, criando a variavel desemprego
agregado_pnad = inner_join(populacao, condicao, by="date") %>% 
  rename(populacao = Valor) %>% 
  mutate(desemprego = desocupada/pea*100) %>% 
  select(date, desemprego)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Visualizando os dados
font_add_google("Ubuntu","Ubuntu")
showtext_auto()

ultimo_valor = round(tail(agregado_pnad$desemprego,1),1)

g1 = ggplot(agregado_pnad, aes(x=date,y=desemprego))+
  geom_line()+
  geom_hline(yintercept = ultimo_valor, colour = 'red', linetype="dashed")+
  theme_bw()+
  theme(
    legend.text = element_text(family = "Ubuntu", color="#000000",size = 8),
    axis.text.y = element_text(family = "Ubuntu", color="#000000",size = 8, hjust=1.25),
    plot.title = element_text(face = "bold", family = "Ubuntu", size = 15),
    plot.caption = element_text(face = "italic", family="Ubuntu"),
    axist.title = element_text(size = 8),
    plot.margin = margin(t=20, r =8,b= 7,l =5),
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.x = element_text(angle=55, hjust = 1),
    panel.grid.major = element_line(color = "gray", size  = 0.25, linetype = "dashed"),#linhas principais
    panel.grid.minor = element_line(color = "lightgray", size = 0.25, linetype = "dotted") #Linhas
  )+
  scale_x_date(breaks = date_breaks("6 months"),
               labels = date_format("%b%y"))+
  annotate("text",
           x=as.Date("2024-11-21"),
           y = 7.5,
           label=paste0(ultimo_valor,"%"),
           colour="red",size=6)+
  annotate("rect", fill = "blue", alpha = 0.2,
           xmin=as.Date("2024-06-01"),
           xmax=as.Date("2025-02-01"),
           ymin = -Inf,
           ymax = Inf)+
  annotate("rect", fill = "blue", alpha = 0.2,
           xmin=as.Date("2021-02-01"),
           xmax=as.Date("2021-06-01"),
           ymin = -Inf,
           ymax = Inf)+
  labs(x="",
       y="%",
       title="Taxa de Desemprego",
       subtitle = "Março-2012/Dezembro-2024",
       caption = "Elaboração: Gladson Rabelo - Fonte: PNAD-Continua - IBGE")

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Informações de Rendimento
urlrendimento = "/t/6390/n1/all/v/5933/p/all"
rendimentos = get_sidra(api=urlrendimento) %>% 
  mutate(date = parse_date(`Trimestre Móvel (Código)`,
                            format="%Y%m")) %>% 
  select(Valor,date)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Visualizando dados
ultimo_valor2=round(tail(rendimentos$Valor,1),1)
g2 = ggplot(rendimentos, aes(x=date,y=Valor))+
  geom_line()+
  geom_hline(yintercept = ultimo_valor2, colour = 'red', linetype="dashed")+
  theme_bw()+
  theme(
    legend.text = element_text(family = "Ubuntu", color="#000000",size = 8),
    axis.text.y = element_text(family = "Ubuntu", color="#000000",size = 8, hjust=1.25),
    plot.title = element_text(face = "bold", family = "Ubuntu", size = 15),
    plot.caption = element_text(face = "italic", family="Ubuntu"),
    axist.title = element_text(size = 8),
    plot.margin = margin(t=20, r =8,b= 7,l =5),
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.x = element_text(angle=55, hjust = 1),
    panel.grid.major = element_line(color = "gray", size  = 0.25, linetype = "dashed"),#linhas principais
    panel.grid.minor = element_line(color = "lightgray", size = 0.25, linetype = "dotted") #Linhas
  )+
  scale_x_date(breaks = date_breaks("6 months"),
               labels = date_format("%b%y"))+
  annotate("text",
           x=as.Date("2024-09-21"),
           y = ultimo_valor2+30,
           label=paste0("R$",ultimo_valor2),
           colour="red",size=6.)+
  labs(x="R$",
       y="",
       title="Rendimento médio mensal real habitualmente recebido",
       subtitle = "Março-2014 / Dezembro-2024",
       caption = "Elaboração: Gladson Rabelo - Fonte: PNAD-Continua - IBGE")
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Rendimento por ocupação
urlocupacao = "/t/6389/n1/all/v/5932/p/all/c11913/31722,31723,31724,31727,96165,96170,96171"
rendimento_ocup = get_sidra(api=urlocupacao)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Tratamento de dados
rendimento_ocup.selec = rendimento_ocup %>% 
  select("date"= `Trimestre Móvel (Código)`,
         "variable"=`Posição na ocupação e categoria do emprego no trabalho principal`,
         "code"=`Posição na ocupação e categoria do emprego no trabalho principal (Código)`,
         "value"=`Valor`) %>% 
  filter(code %in% c("31722","31723","31724","31727","96165","96170","96171")) %>% 
  group_by(variable) %>% 
  mutate(date=as_date(paste0(date, "01")),
         variable = recode(variable,
                           "Empregado no setor privado, exclusive trabalhador doméstico - com carteira de trabalho assinada" = 
                             "Privado com carteira",
                           "Empregado no setor privado, exclusive trabalhador doméstico - sem carteira de trabalho assinada" = 
                             "Privado sem carteira")) %>% 
  drop_na() %>% 
  select(-code)
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Visualizando os dados
g3 = ggplot(rendimento_ocup.selec, aes(x=date,y=value, color = variable))+
  geom_line(size = 1)+
  theme_bw()+
  ylim(0,11000)+
  theme(
    legend.text = element_text(family = "Ubuntu", color="#000000",size = 8),
    legend.key.size = unit(0.5,"lines"), #Ajusta tamanho icones da legenda
    axis.text.y = element_text(family = "Ubuntu", color="#000000",size = 8, hjust=1.25),
    plot.title = element_text(face = "bold", family = "Ubuntu", size = 15),
    plot.caption = element_text(face = "italic", family="Ubuntu"),
    plot.subtitle = element_text(face = "italic", family = "Ubuntu"),
    axist.title = element_text(size = 8),
    plot.margin = margin(t=20, r =8,b= 7,l =5),
    legend.position = c(0.03, .98), #ajuste posição legenda
    legend.justification = c(0,1), #justificação da legenda
    panel.grid = element_blank(),
    axis.text.x = element_text(angle=55, hjust = 1),
    panel.grid.major = element_line(color = "gray", size  = 0.25, linetype = "dashed"),#linhas principais
    panel.grid.minor = element_line(color = "lightgray", size = 0.25, linetype = "dotted") #Linhas
  )+
  scale_x_date(breaks = date_breaks("6 months"),
               labels = date_format("%b%y"))+
  labs(x="",
       y="R$",
       title="Rendimento médio do trabalhador principal, habitualmente recebido.",
       subtitle = "Março-2012 / Dezembro-2024",
       caption = "Elaboração: Gladson Rabelo - Fonte: PNAD-Continua - IBGE",
       color ="")
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# População oculpada
urlpo = "/t/6320/n1/all/v/4090/p/all/c11913/allxt"
po = get_sidra(api=urlpo)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Tratamento de dados
po_ocupada = po %>% 
  select("date"= `Trimestre Móvel (Código)`,
         "variable"=`Posição na ocupação e categoria do emprego no trabalho principal`,
         "value"=`Valor`,
         "code"=`Posição na ocupação e categoria do emprego no trabalho principal (Código)`
         ) %>% 
  mutate(date= parse_date(date,
                          format="%Y%m")) %>% 
  filter(code %in% c("31722","31723","31724","31727","96170","96171")) %>% 
  select(-code)

po_ocupada$variable[
  po_ocupada$variable == "Empregado no setor privado, exclusive trabalhador doméstico - com carteira de trabalho assinada"] = 
                      "Privado com carteira"
po_ocupada$variable[
  po_ocupada$variable == "Empregado no setor privado, exclusive trabalhador doméstico - sem carteira de trabalho assinada"] = 
                      "Privado sem carteira"

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
g4 = ggplot(po_ocupada, aes(x=date,y=value, color = variable))+
  geom_line()+
  theme_bw()+
  facet_wrap(~variable, scales = "free")+
  theme(
    legend.text = element_text(family = "Ubuntu", color="#000000",size = 8),
    axis.text.y = element_text(family = "Ubuntu", color="#000000",size = 8, hjust=1.25),
    plot.title = element_text(face = "bold", family = "Ubuntu", size = 15),
    plot.caption = element_text(face = "italic", family="Ubuntu"),
    plot.subtitle = element_text(face = "italic", family = "Ubuntu"),
    axist.title = element_text(size = 8),
    plot.margin = margin(t=20, r =8,b= 7,l =5),
    legend.position = "none", 
    panel.grid = element_blank(),
    axis.text.x = element_text(angle=55, hjust = 1),
    panel.grid.major = element_line(color = "gray", size  = 0.25, linetype = "dashed"),#linhas principais
    panel.grid.minor = element_line(color = "lightgray", size = 0.25, linetype = "dotted") #Linhas
  )+
  labs(x="",
       y="mil ocupados",
       title="Posição na ocupação e categoria do emprego no trabalho principal",
       subtitle = "Março-2012 / Dezembro-2024",
       caption = "Elaboração: Gladson Rabelo - Fonte: PNAD-Continua - IBGE")
```


```{r, message=FALSE, warning=FALSE, echo=FALSE,fig.width=7, fig.height=7}
#Painel de gráficos

#gridExtra::grid.arrange(g1,g2)

```


```{r, message=FALSE, warning=FALSE, echo=FALSE,fig.width=8, fig.height=8}

#gridExtra::grid.arrange(g3,g4)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE,fig.width=16, fig.height=11}

gridExtra::grid.arrange(g1,g2,g3,g4)

```